6 new data sets
OpenIntroStat/openintro pull request #67
Opened 2023-01-06 17:29 UTC by npaterno

Hi Mine, 

I noticed that the pr I had submitted for these was a mess (had a bunch of old commits) so I closed that, reforked openintro and created this pr. It includes 6 new data sets that were developed over the summer.

2023-03-08 17:44 UTC, mine-cetinkaya-rundel requested changes
The datasets look great! There are lots of little things in the code examples, some I've commented on, some I haven't but can be addressed by running the styler (https://styler.r-lib.org/) on the code. With those changes I can do one more quick round of review and this should be good to go.

2023-03-08 17:44 UTC, mine-cetinkaya-rundel commented on R/data-lecture_learning.R
> +#'   \item{gender}{Gender of student.}
Is this reported gender by the student? How was it determined? If binary, it would be good to indicate that it was how the study recorded it.

2023-03-08 17:44 UTC, mine-cetinkaya-rundel commented on R/data-lecture_learning.R
> +#'  scale_fill_manual(values = c(IMSCOL["blue", "full"], IMSCOL["pink", "full"])) +
For the examples I suggest we use the default color scale, since it's more important that they're accessible to new learners than they look like the figures in the book.

2023-03-08 17:44 UTC, mine-cetinkaya-rundel commented on R/data-lego_population.R
> +#' Data from their article was scrapped from multiple sources including brickset.com
What is the license / terms of reuse for these data? We should have something here that indicates it. I would also recommend using the `@source` tag for listing all of the sources.

2023-03-08 17:44 UTC, mine-cetinkaya-rundel commented on R/data-lego_sample.R
> +#' Data from their article was scrapped from multiple sources including brickset.com
Same comment as other lego dataset.

2023-03-08 17:44 UTC, mine-cetinkaya-rundel commented on R/data-lego_sample.R
> +#' small<-filter(lego_sample, theme =="Friends" | theme == "City" )
```suggestion
#' small <- filter(lego_sample, theme =="Friends" | theme == "City" )
```

2023-03-08 17:44 UTC, mine-cetinkaya-rundel commented on R/data-lego_population.R
> +#' small<-filter(lego_population, theme =="Friends" | theme == "City" )
```suggestion
#' small <- lego_population %>%
#'   filter(theme == "Friends" | theme == "City")
```

2023-03-08 17:44 UTC, mine-cetinkaya-rundel commented on R/data-lego_population.R
> +#'     x= "Pieces in the Set",
```suggestion
#'     x = "Pieces in the Set",
```

2023-03-08 17:44 UTC, mine-cetinkaya-rundel commented on R/data-nba_finals.R
> +#'    top_n(5)
```suggestion
#' nba_finals %>% 
#'    pivot_longer(
#'      cols = c("western_coach", "eastern_coach"), 
#'      names_to = "conference", values_to = "coach"
#'    ) %>% 
#'    count(coach) %>% 
#'    arrange(-n) %>% 
#'    top_n(5)
```

2023-03-08 17:44 UTC, mine-cetinkaya-rundel commented on R/data-nba_finals.R
> +#'    top_n(5)
`top_n()` is superseded, use `slice_head()`

2023-03-08 17:44 UTC, mine-cetinkaya-rundel commented on R/data-fish_age.R
> +#'   select(-one_year_old)
```suggestion
#' fish_age %>% 
#'   count(year, location, one_year_old) %>% 
#'   filter(one_year_old == "yes") %>% 
#'   pivot_wider(names_from = location, values_from = n) %>% 
#'   select(-one_year_old)
```

2023-03-08 17:44 UTC, mine-cetinkaya-rundel commented on R/data-lecture_learning.R
> +#'  summarize(average_memory = mean(memory), count = n())
```suggestion
#' lecture_learning %>%
#'   group_by(method, gender) %>%
#'   summarize(average_memory = mean(memory), count = n())
```

2023-03-09 16:46 UTC, npaterno commented
@mine-cetinkaya-rundel Requested changes complete. The only one not addressed is about the terms of use/license for the lego data. I couldn't find one but was able to find the data freely available online (sources added).

2023-03-09 16:52 UTC, npaterno commented
Looks like the checks are failing for not being able to install R (Ubuntu) or not being able to install dependencies like ggplot2 (Mac and Windows). It's passing on both my laptop and desktop so not sure what's going on.

2023-03-09 16:53 UTC, mine-cetinkaya-rundel commented
We might need to update the action, I haven't touched them in a while. I can take a look while I review, but if it's of interest, feel free to tinker as well.

2023-03-17 13:05 UTC, mine-cetinkaya-rundel commented
@npaterno Made a handful of edits directly. This should be good to merge once the checks pass. Thank you and thanks to the data hunters!

2023-03-22 15:08 UTC, merged